// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyfVT-hdc1UIaZcHyjy6iWoyeNmDbWAZE',
    appId: '1:943827568635:web:d299dda2d98620d27c2d5e',
    messagingSenderId: '943827568635',
    projectId: 'sketchapp-58768',
    authDomain: 'sketchapp-58768.firebaseapp.com',
    storageBucket: 'sketchapp-58768.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBInD8mcktqeHdl7MBkwXy4KVXJhtMc4aQ',
    appId: '1:943827568635:android:d1f18fdafa8b2eac7c2d5e',
    messagingSenderId: '943827568635',
    projectId: 'sketchapp-58768',
    storageBucket: 'sketchapp-58768.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBESFIUFZSBPFfgDyhyZYMgsXPmf6wzqtc',
    appId: '1:943827568635:ios:88930b5032c7df327c2d5e',
    messagingSenderId: '943827568635',
    projectId: 'sketchapp-58768',
    storageBucket: 'sketchapp-58768.appspot.com',
    iosBundleId: 'com.example.sketchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBESFIUFZSBPFfgDyhyZYMgsXPmf6wzqtc',
    appId: '1:943827568635:ios:88930b5032c7df327c2d5e',
    messagingSenderId: '943827568635',
    projectId: 'sketchapp-58768',
    storageBucket: 'sketchapp-58768.appspot.com',
    iosBundleId: 'com.example.sketchApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyfVT-hdc1UIaZcHyjy6iWoyeNmDbWAZE',
    appId: '1:943827568635:web:8bd1ded607eae9517c2d5e',
    messagingSenderId: '943827568635',
    projectId: 'sketchapp-58768',
    authDomain: 'sketchapp-58768.firebaseapp.com',
    storageBucket: 'sketchapp-58768.appspot.com',
  );
}
